name: Check against Fedora dist-git

on:
  push:
  workflow_dispatch:
  schedule:
    - cron: '15 4 * * *'

jobs:
  check-fedora:
    runs-on: ubuntu-slim
    timeout-minutes: 5
    permissions:
      contents: write
      pull-requests: write
    steps:
      - uses: actions/checkout@v7
        with:
          fetch-depth: 0
      - run: git remote add fedora-dist-git https://src.fedoraproject.org/rpms/bash.git
      - run: git fetch fedora-dist-git
      - run: git branch -r --list 'fedora-dist-git/f[1-9]*' | sed 's%^ *fedora-dist-git/f%%' | sort -rn | head | tee /dev/stderr | head -1 | sed 's/^/LATEST_FEDORA_BRANCH=f/' >> "$GITHUB_ENV"
      - run: printf '%s\n' "$LATEST_FEDORA_BRANCH"
      - run: |
          if git merge-base --is-ancestor "fedora-dist-git/$LATEST_FEDORA_BRANCH" "$GITHUB_REF" ; then
            echo "::notice::No new commits found in Fedora dist-git $LATEST_FEDORA_BRANCH branch."
            exit 0
          fi
          echo "::notice::New commits in Fedora dist-git $LATEST_FEDORA_BRANCH branch."
          git push origin "fedora-dist-git/$LATEST_FEDORA_BRANCH:refs/heads/$LATEST_FEDORA_BRANCH"
          if gh pr list -B "$GITHUB_REF_NAME" | tee /dev/stderr | grep -q . ; then
            echo "::warning::There already is an unmerged pull request, resolve it first."
            exit 9
          fi
          MERGE_HEAD="$LATEST_FEDORA_BRANCH"
          BODY=
          git config user.name 'Jan Pazdziora'
          git config user.email jan.pazdziora@code.adelton.com
          if git merge -m "Merge remote-tracking branch 'fedora-dist-git/$LATEST_FEDORA_BRANCH' into $GITHUB_REF_NAME" "fedora-dist-git/$LATEST_FEDORA_BRANCH" ; then
            NEW_HEAD="$( git rev-parse --short HEAD )"
            MERGE_HEAD="$LATEST_FEDORA_BRANCH-$NEW_HEAD"
            git push origin "HEAD:refs/heads/$MERGE_HEAD"
            BODY="Review and fast-forward-merge this PR with a \`/merge-ff\` comment, then remove the temporary **$MERGE_HEAD** branch."
          else
            BODY="We were not able to create a merge commit, you will need to merge manually."
          fi
          PR_URL="$( gh pr create -B "$GITHUB_REF_NAME" -H "$MERGE_HEAD" --title "Merge remote-tracking branch 'fedora-dist-git/$LATEST_FEDORA_BRANCH' into $GITHUB_REF_NAME" --body "$( printf '%s\n\n%s' "$BODY" "Created by $RUN_ID_URL")" )"
          echo "::notice::Filed pull request $PR_URL, consider merging."
        env:
          GITHUB_TOKEN: ${{ github.token }}
          RUN_ID_URL: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}

